### ISSUE TITLE
How to adjust the parameters to improve clarity and display colors correctly?

### ISSUE THREAD

**Issue by sgf** [ReferenceType/H264Sharp#3]
![动画0091](https://github.com/ReferenceType/H264Sharp/assets/2557696/a95ec997-08ba-4b94-97ca-28e88791efa6)

the left is encoded/decoded by H264Sharp 
the right is direct draw from capture.

you can see the Buttone Border Color

**Comment by sgf** [comment]
```C#

        encoder = new();
        encoder.ConverterNumberOfThreads = 2;
        //decoder.EnableSSEYUVConversion = true;

        decoder = new H264Decoder();
        decoder.ConverterNumberOfThreads = 2;
        decoder.Initialize();
        //TagSVCDecodingParam decParam = new TagSVCDecodingParam();
        //decParam.uiTargetDqLayer = 0xff;
        //decParam.eEcActiveIdc = ERROR_CON_IDC.ERROR_CON_FRAME_COPY_CROSS_IDR;
        //decParam.sVideoProperty.eVideoBsType = VIDEO_BITSTREAM_TYPE.VIDEO_BITSTREAM_SVC;
        //decoder.Initialize(decParam);
        //decoder.Initialize(new TagSVCDecodingParam() { });


        var fps = 10;
        var factor = 0.5;
        var bitrate = (int)(xCapture.Width * xCapture.Height * fps * factor);
        ConfigType configNo = ConfigType.ScreenCaptureBasic;//Advanced
        encoder.Initialize(xCapture.Width, xCapture.Height, bitrate, 10, configNo);//200_000_000 4_992_000 1_500_000 
```

this is my encoder/decoder setting

**Comment by ReferenceType** [comment]
If I understood you well, It seems you are asking about high quality encoding because there are some quality loss.

This is related to implementation detail of Openh264. 
`ScreenCapture` mode tend to have lower quality, it is optimized for low data transfer rate. `CameraCapture` mode is more accurate but uses more data, you can try that.
To clarify Advanced modes, `CameraCaptureAdvanced` does more processing and should produce better results with the cost of more CPU usage.

Now another point is the fps, this is another implementation detail of OpenH264. Fps number can effect quality, if you have bitrate control mode on. In general, you should match the fps number with the actual fps that is coming from your image source(i.e.Capture).

here you can see the parameters in detail in native side regarding `ConfigType`:
https://github.com/ReferenceType/H264Sharp/blob/254467eb716457472cebfd912a80bea4d8eb3496/H264SharpNative/Encoder.cpp#L140

Regarding the off-color I also noticed some blue off-coloring on text with white background. I only have it if the image is sourced from screen capture and the artifact appears to be when lines are single pixel width. Seems to me color sampling issue due to YUV420, I will investigate this

**Comment by sgf** [comment]
I have tried these settings, but they don't seem to work.

```C#
        ConfigType configNo = ConfigType.ScreenCaptureAdvanced;//Advanced
        encoder.Initialize(xCapture.Width, xCapture.Height, 200_000_000, 10, configNo);//200_000_000 4_992_000 1_500_000 
        encoder.SetOption(ENCODER_OPTION.ENCODER_OPTION_RC_MODE, 0);//Quality Mode
```

**Comment by ReferenceType** [comment]
I send you a sample of decoded image from screen share functionality of P2PVideocall application.
this is between two pcs
Original:
![image](https://github.com/ReferenceType/H264Sharp/assets/109621184/fa99bdae-89ed-40a0-b73d-5c29d24090e1)


Encoded and decoded:
![image](https://github.com/ReferenceType/H264Sharp/assets/109621184/95246191-56ba-4c5e-9c4f-865cfc272f4b)

The color offsets are H264 encoder artifacts. its not lossless encoding. 
I will check the color space conversions and get back here, but I'm almost sure this is from the encoder itself.
Ask cisco if you have further questions.

**Comment by sgf** [comment]
OK, thank you very much for your support.
